# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0c71b30df5a61dc14c173c1b1d37e66079477a56c56d1f83012767382cd099c46586add04aeb533af050dd119e999e7c5975138be9452f362d2ffe640dc1aab

test:
  secret_key_base: e607bff5323a84f5929dafeb3c63d9cef3afa7eddd200565a9f08134fe2511d46d3146273000afe7e876b19ba31152f61e0dd836b5ef103f0e158975557ebacc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
